development:
  adapter: mysql2
  encoding: utf8
  database: req
  pool: 5
  username: root
  password: '599199'
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: req
  pool: 5
  username: root
  password: '599199'
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: < %= ENV['DB_BASE'] %>
  username: < %= ENV['DB_USER'] %>
  password: < %= ENV['DB_PASS'] %>
  host: < %= ENV['DB_HOST'] %>